.plt.util.plt:`plt 2:(`plot;2);
.plt.util.mplt:`plt 2:(`multiplot;2);
.plt.util.hm:`plt 2:(`hm;1);
.plt.util.hmupd:`plt 2:(`hmupd;2);
.plt.plt:{.plt.util.plt[`float$x;`float$y]};
.plt.mplt:{.plt.util.mplt[`float$x;`float$y]};
.plt.hm:{.plt.util.hm[`float$x]};
.plt.hmupd:{.plt.util.hmupd[x;`float$y]};
.plt.livehm:`plt 2:(`glivehm;1);
.plt.gifhm:`plt 2:(`ggifhm;1);
.plt.close:`plt 2:(`gclose;1);
.plt.cbrange:`plt 2:(`cbrange;3);